CREATE DATABASE IF NOT EXISTS uts_iot_hidroponik_db;
USE uts_iot_hidroponik_db;

CREATE TABLE IF NOT EXISTS data_sensor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  suhu FLOAT NOT NULL,
  humidity FLOAT NOT NULL,
  lux INT DEFAULT 0,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);